### ISSUE TITLE
Revue des expositions numériques

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/reframe#14]
Une issue pour laisser les idées, questions et remarques à garder en tête durant l'analyse des expositions numériques.

**Comment by WilliamDiakite** [comment]
En prévision de la séance de travail avec @ZoeRenaudie, le 12/02/2024 : 

- Reframe traite des expositions virtuelles et (plus généralement?) des publications savantes. 
- Penser à prendre des notes sur la manière dont la dégradation des contenues est gérée.
- Est-ce que les différents types de contenus permettent demande à définir des layouts ou des intéractions particulières ? ie. une vue d'exposition n'a pas le même statut qu'une numérisation d'une pièce d'archive, est-ce qu'il y a besoin de penser des stratégies différentes pour leur mise ? Ou est-ce qu'on risque d'être trop spécifique ?

**Comment by ZoeRenaudie** [comment]
Suite à notre point hier, j'ai créé le doc diapo dans google pour donner des exemple de dégradations que nous trouvons dans les expositions en ligne : 
https://docs.google.com/presentation/d/1ZbWHkWfATxSfg0qFvZl099_Yy5nxdOPUkCw2Ne28ElA/edit?usp=sharing

@WilliamDiakite peux-tu me confirmer que ça t'est utile?
